#!/bin/bash

OP1=/home/temp/scan-$(date +"%F-%T".txt)

echo -e "\n"|tee -a $OP1 

for FILE in $(find /var/cpanel/userdata/ -type f | xargs grep documentroot | awk -F":" '{print$1}' | egrep -v "(cache|SSL|nobody)" | xargs grep documentroot | awk -F":" '{print $3}'); do echo -e "Scan location:\t$FILE\n" | tee -a $OP1 

/usr/local/cpanel/3rdparty/bin/clamscan -ir -d /root/lw-yara/lw.hdb -d /root/lw-yara/lw-rules_index.yar $FILE | tee -a $OP1; echo -e "\n" | tee -a $OP1 ; done; echo -e "Scan output file can be found here: $OP1"
