#!/bin/bash

#making log location
if [[ -e /home/scan ]];then #then pwd exists
	echo -e 
else
mkdir -p /home/scan
fi

#set sigdir
sigdir=/home/scan/lw-yara

if [[ -e /home/scan/lw-yara/lw.hdb ]]; then #rules installed, run update
	cd $sigdir
	git pull
else git clone https://github.com/Hestat/lw-yara.git $sigdir
fi
	
#creating log file
OP1=/home/scan/scan-$(date +%y%m%d-%H%M.txt)

echo -e "\n"|tee -a $OP1 

if [[ -x $(which whmapi1) ]]; then #cpanel

	if [[ -x $(which clamscan) ]]; then #clamav installed
		for FILE in $(find /var/cpanel/userdata/ -type f | xargs grep documentroot | awk -F":" '{print$1}' | egrep -v "(cache|SSL|nobody)" | xargs grep documentroot | awk -F":" '{print $3}'); do echo -e "Scan location:\t$FILE\n" | tee -a $OP1 
		clamscan -ir --no-summary -d /root/lw-yara/lw.hdb -d /root/lw-yara/lw-rules_index.yar $FILE | tee -a $OP1; echo -e "\n" | tee -a $OP1 ; done; echo -e "Scan output file can be found here: $OP1"
	else echo -e "trying to link to existing clamscan binary"
		ln -s /usr/local/cpanel/3rdparty/bin/clamscan /usr/bin/clamscan 
		ln -s /usr/local/cpanel/3rdparty/bin/freshclam /usr/bin/freshclam
		if [[ -x $(which clamscan) ]]; then 
			echo -e "success, please restart to scan"
			else echo -e "clamav not installed please install"
		fi
	fi
else
	echo -e "not cpanel, exiting"
fi
