#!/bin/bash

###############################setup##################################
#choose y/N
yesno(){ read -p "$question " choice;case "$choice" in y|Y|yes|Yes|YES ) decision=1;; n|N|no|No|NO ) decision=0;; * ) echo "invalid" && yesno; esac; }

#making log location
if [[ -e /usr/local/scan ]];then #then pwd exists
	echo -e 
else
mkdir -p /usr/local/scan
fi

#set sigdir
sigdir=/usr/local/scan/lw-yara

if [[ -e /usr/local/scan/lw-yara/lw.hdb ]]; then #rules installed, run update
	cd $sigdir
	git pull
else git clone https://github.com/Hestat/lw-yara.git $sigdir
fi

scandir=/usr/local/scan

########################## install maldet if not installed ################################
#
#if [[ -x $(which maldet) ]]; then #maldet installed adding maldet sigs
#	echo -e "Maldet is not installed would you like to install now?"
#	yesno 
#	if [[ $decision = 1 ]];then 
#	pushd /usr/local/src/
#	rm -vrf /usr/local/src/maldetect-*
#	rm -vrf /usr/local/src/linux-malware-detect*
#	wget http://www.rfxn.com/downloads/maldetect-current.tar.gz
#	tar -zxvf maldetect-current.tar.gz
#	cd maldetect-*
#	sh ./install.sh
#	maldet --update-ver
#	#sed patch - commands added to address current problem with maldet overriding values in the conf file
#	sed -i 's/quarantine_hits=\"1\"/quarantine_hits=\"0\"/' /usr/local/maldetect/conf.maldet
#	sed -i 's/quarantine_clean=\"1\"/quarantine_clean=\"0\"/' /usr/local/maldetect/conf.maldet
#	sed -i 's/email_alert=\"1\"/email_alert=\"0\"/' /usr/local/maldetect/conf.maldet
#	sed -i 's/email_addr=\"you@domain.com\"/email_addr=\"\"/' /usr/local/maldetect/conf.maldet
#	#end sed patch
#	maldet --update
#	if [ -e /usr/local/cpanel/3rdparty/bin/clamscan ]
#	then
#	ln -s /usr/local/cpanel/3rdparty/bin/clamscan /usr/bin/clamscan 
#	ln -s /usr/local/cpanel/3rdparty/bin/freshclam /usr/bin/freshclam
#	if [ ! -d /var/lib/clamav ]
#	then mkdir /var/lib/clamav
#	fi
#	ln -s /usr/local/cpanel/3rdparty/share/clamav/main.cld /var/lib/clamav/main.cld
#	ln -s /usr/local/cpanel/3rdparty/share/clamav/daily.cld /var/lib/clamav/daily.cld
#	ln -s /usr/local/cpanel/3rdparty/share/clamav/bytecode.cld /var/lib/clamav/bytecode.cld 
#	else
#	echo -e "\n\e[31mClamAV does not appear to be installed through cPanel.\nThe ClamAV definitions will not be used.\e[39m\n"
#	fi
#	popd
#else #continue
#	echo -e
#fi

###########################################################################################33
if [[ -x $(which maldet) ]]; then #maldet installed adding maldet sigs
	sigdir2=/usr/local/maldetect/sigs
else
	echo -e #not installed
fi

######################   create formatting #################################
div(){
  for ((i=0;i<$1;i++)); do printf '='; done;
}

header(){
	echo -e "\n$(div 40)\n"
}

header2=$(echo -e "$(div 3)")

title(){
echo -e "                      __________________"
echo -e "                      \                 \ "
echo -e "                       \                 \ "
echo -e "                        \            )    \ "
echo -e "                         \          ).(    \ "
echo -e "       /-------------------------).(.(------"
echo -e "     //---------------//   (     ).(.   //  |"
echo -e "    //                //    (.)   ).(. // __|"
echo -e "   //               //   ) .( .( ).)) //    ||"
echo -e "  //               // ).( .( .) .(.).//     ||"
echo -e " //_______________//  ^^^^^^^^^^^^^^//      ||"
echo -e "------------------------------------/ ------ |"
echo -e "| Blazescan   |         |  Another  |        |"    
echo -e "| AMS Software|         |  Malware  |        |"   
echo -e "|--------------         |  Scanner  |        |"   
echo -e "|                       ------------|        |"
echo -e "----------------------------------------------" 
echo -e "Sometimes you need to burn it down and start fresh"
}

#########################   help menu   #####################################

helpmenu(){
	echo -e "Blazescan is a malware scanning tool that uses clamav and custom malware databases\n"
	echo -e "If you run blazescan without and arguments it will present a simple scanning menu\n"
	echo -e "-a will scan all cpanel accounts\n"
	echo -e "-u will scan all scan the specified cpanel user\n"
	echo -e "-l will show the results of the last scan\n"
	echo -e "-t will display ctime of the hits in tehe last scan\n"
	echo -e "-h will display this help menu\n"
}

###########################   scan functions    ################################

cpanelallscan1(){
		for FILE in $(find /var/cpanel/userdata/ -type f | xargs grep documentroot | awk -F":" '{print$1}' | egrep -v "(cache|SSL|nobody)" | xargs grep documentroot | awk -F":" '{print $3}'); do echo -e "Scan location:\t$FILE\n" | tee -a $OP1 
		clamscan -ir -d /usr/local/scan/lw-yara/lw.hdb -d /usr/local/scan/lw-yara/lw-rules_index.yar $FILE | tee -a $OP1; echo -e "\n" | tee -a $OP1 ; done; echo -e "Scan output file can be found here: $OP1"
}


cpanelallscan2(){
		for FILE in $(find /var/cpanel/userdata/ -type f | xargs grep documentroot | awk -F":" '{print$1}' | egrep -v "(cache|SSL|nobody)" | xargs grep documentroot | awk -F":" '{print $3}'); do echo -e "Scan location:\t$FILE\n" | tee -a $OP1 
		clamscan -ir --no-summary -d /usr/local/maldetect/sigs -d /usr/local/scan/lw-yara/lw.hdb -d /usr/local/scan/lw-yara/lw-rules_index.yar $FILE | tee -a $OP1; echo -e "\n" | tee -a $OP1 ; done; echo -e "Scan output file can be found here: $OP1"
}

singlecpanelscan1a(){
                for FILE2 in $(find /var/cpanel/userdata/$user -type f | xargs grep documentroot | awk -F":" '{print$1}' | egrep -v "(cache|SSL|nobody)" | xargs grep documentroot | awk -F":" '{print $2}'); do echo -e "Scan location:\t$FILE2\n" | tee -a $OP2
                clamscan -ir  --no-summary -d  /usr/local/scan/lw-yara/lw.hdb -d  /usr/local/scan/lw-yara/lw-rules_index.yar $FILE2 | tee -a $OP2; echo -e "\n" | tee -a $OP2;done; echo -e "Scan output file can be found here: $OP2"
}

singlecpanelscan2a(){
                for FILE2 in $(find /var/cpanel/userdata/$user -type f | xargs grep documentroot | awk -F":" '{print$1}' | egrep -v "(cache|SSL|nobody)" | xargs grep documentroot | awk -F":" '{print $2}'); do echo -e "Scan location:\t$FILE2\n" | tee -a $OP2
                clamscan -ir  --no-summary -d /usr/local/maldetect/sigs -d  /usr/local/scan/lw-yara/lw.hdb -d  /usr/local/scan/lw-yara/lw-rules_index.yar $FILE2 | tee -a $OP2; echo -e "\n" | tee -a $OP2;done; echo -e "Scan output file can be found here: $OP2"
}

singlecpanelscan1b(){
                for FILE2 in $(find /var/cpanel/userdata/$user -type f | xargs grep documentroot | awk -F":" '{print$1}' | egrep -v "(cache|SSL|nobody)" | xargs grep documentroot | awk -F":" '{print $3}'); do echo -e "Scan location:\t$FILE2\n" | tee -a $OP2
                clamscan -ir  --no-summary -d  /usr/local/scan/lw-yara/lw.hdb -d  /usr/local/scan/lw-yara/lw-rules_index.yar $FILE2 | tee -a $OP2; echo -e "\n" | tee -a $OP2;done; echo -e "Scan output file can be found here: $OP2"
}

singlecpanelscan2b(){
                for FILE2 in $(find /var/cpanel/userdata/$user -type f | xargs grep documentroot | awk -F":" '{print$1}' | egrep -v "(cache|SSL|nobody)" | xargs grep documentroot | awk -F":" '{print $3}'); do echo -e "Scan location:\t$FILE2\n" | tee -a $OP2
                clamscan -ir  --no-summary -d /usr/local/maldetect/sigs -d  /usr/local/scan/lw-yara/lw.hdb -d  /usr/local/scan/lw-yara/lw-rules_index.yar $FILE2 | tee -a $OP2; echo -e "\n" | tee -a $OP2;done; echo -e "Scan output file can be found here: $OP2"
}

#############################  time stamps and other things ###################

list(){
	grep UNOFFICIAL $(find /usr/local/scan/ -maxdepth 1 -name '*.txt' -type f -exec stat -c "%y %n" {} + | sort -r | head -n1 |awk '{print$4}')
}

timestamps(){
	grep UNOFFICIAL $(find /usr/local/scan/ -maxdepth 1 -name '*.txt' -type f -exec stat -c "%y %n" {} + | sort -r | head -n1 |awk '{print$4}') | cut -d : -f1 | xargs stat -t --format=%z,%n
}
############################# flags for running ###############################

while getopts ":ahltu:" opt; do
  case ${opt} in
    h ) # process option h to display help menu
	    helpmenu
	    exit 0
      ;;
    u ) # process option u for individual cpanel account
	    user=$OPTARG
		OP2=/usr/local/scan/$user-$(date +%F-%H%M.txt)
		echo -e "\n"|tee -a $OP2
		if [[ -x $(which maldet) ]];then 
			echo -e "maldet detected, using maldet and lw-yara signatures"
			if [[ $(find /var/cpanel/userdata/$user -type f | xargs grep documentroot |awk -F":" '{print$1}' | egrep -v "(cache|SSL|nobody)" | xargs grep documentroot | wc -l) -eq "1" ]]; then 
                       			singlecpanelscan2a
                       	else
                       			singlecpanelscan2b
                       	fi; 
                else
                        echo -e "using only lw-yara signatures"
                        if [[ $(find /var/cpanel/userdata/$user -type f | xargs grep documentroot |awk -F":" '{print$1}' | egrep -v "(cache|SSL|nobody)" | xargs grep documentroot | wc -l) -eq "1" ]]; then 
                       			singlecpanelscan1a
                       	else
                       			singlecpanelscan1b
				fi
			fi
			exit 0;;
	a ) # -a option to scan all cpanel accounts
		#creating log file
		OP1=/usr/local/scan/scan-$(date +%F-%H%M.txt)
		echo -e "\n"|tee -a $OP1
		if [[ -x $(which maldet) ]]; then 
			echo -e "maldet detected, using maldet and lw-yara signatures"
			cpanelallscan2
		else
			echo -e "using only lw-yara signatures"
			cpanelallscan1
		fi
		exit 0;;

	l ) list
		exit 0;;
	t ) timestamps
		exit 0;;

    \? ) echo "Usage: cmd [-h help] [-u cpanel user] [ -a scan all cpanel account] [-l list last scan results] [-t list create time of hits]"
      ;;
  esac
done

#############################   begin main   ##################################

if [[ -x $(which whmapi1) ]]; then #cpanel

	#begin menu for cpanel options
	while true
	do
		clear
		header
		#title
		echo -e
		echo -e "Please select scan you would like to run\n"
		echo -e "Select 1 to scan all Cpanel accounts and Docroots\n"
		echo -e "Select 2 to scan individual account\n"
		echo -e "Select 3 to exit\n"
		echo -e "Blazescan can also be run with flags\n"
		echo "Usage: cmd [-h help] [-u cpanel user] [ -a scan all cpanel account]"
		header
read answer
case "$answer" in

	
	1) if [[ -x $(which clamscan) ]]; then #clamav installed
		#creating log file
		OP1=/usr/local/scan/scan-$(date +%F-%H%M.txt)
		echo -e "\n"|tee -a $OP1
		if [[ -x $(which maldet) ]]; then 
			echo -e "maldet detected, using maldet and lw-yara signatures"
			cpanelallscan2
		else
			echo -e "using only lw-yara signatures"
			cpanelallscan1
		fi
	else echo -e "trying to link to existing clamscan binary"
		ln -s /usr/local/cpanel/3rdparty/bin/clamscan /usr/bin/clamscan 
		ln -s /usr/local/cpanel/3rdparty/bin/freshclam /usr/bin/freshclam
		if [[ -x $(which clamscan) ]]; then 
			echo -e "success, please restart to scan"
			else echo -e "clamav not installed please install"
		fi
	fi;;

	2) 	echo "What is the cpanel user?"
		read user
		#creating log file
		OP2=/usr/local/scan/$user-$(date +%F-%H%M.txt)
		echo -e "\n"|tee -a $OP2
		if [[ -x $(which maldet) ]];then 
			echo -e "maldet detected, using maldet and lw-yara signatures"
			if [[ $(find /var/cpanel/userdata/$user -type f | xargs grep documentroot |awk -F":" '{print$1}' | egrep -v "(cache|SSL|nobody)" | xargs grep documentroot | wc -l) -eq "1" ]]; then 
                       			singlecpanelscan2a
                       	else
                       			singlecpanelscan2b
                       	fi; 
                else
                        echo -e "using only lw-yara signatures"
                        if [[ $(find /var/cpanel/userdata/$user -type f | xargs grep documentroot |awk -F":" '{print$1}' | egrep -v "(cache|SSL|nobody)" | xargs grep documentroot | wc -l) -eq "1" ]]; then 
                       			singlecpanelscan1a
                       	else
                       			singlecpanelscan1b
                       	fi; 
		fi;;			

	3) exit;;
	esac
	echo -e "Press Enter to return to menu"
	read input
done
else
	echo -e "not cpanel, exiting"
fi
